version: '3'

vars:
  HOSTNAME: registry.terraform.io
  NAMESPACE: darshan-rambhia
  NAME: filesync
  BINARY: terraform-provider-{{.NAME}}
  VERSION: 0.1.0
  OS_ARCH:
    sh: echo "$(go env GOOS)_$(go env GOARCH)"
  BUILD_DIR: ./dist
  INSTALL_DIR: ~/.terraform.d/plugins/{{.HOSTNAME}}/{{.NAMESPACE}}/{{.NAME}}/{{.VERSION}}/{{.OS_ARCH}}

tasks:
  default:
    desc: Build the provider
    cmds:
      - task: build

  build:
    desc: Build the provider binary
    deps: [lint]
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.BINARY}}
    sources:
      - ./**/*.go
    generates:
      - "{{.BUILD_DIR}}/{{.BINARY}}"

  install:
    desc: Install provider locally for testing
    deps: [build]
    cmds:
      - mkdir -p {{.INSTALL_DIR}}
      - cp {{.BUILD_DIR}}/{{.BINARY}} {{.INSTALL_DIR}}/{{.BINARY}}

  test:
    desc: Run acceptance tests with 5 parallel containers (requires Docker)
    cmds:
      - go test -v ./tests/acceptance -timeout 30m -parallel-containers=5

  test:unit:
    desc: Run unit tests only (skip acceptance tests)
    cmds:
      - go test -v -short ./internal/...

  test:acceptance:
    desc: Run acceptance tests with configurable parallelism
    vars:
      PARALLEL: '{{.PARALLEL | default "5"}}'
    env:
      TF_ACC: "1"
    cmds:
      - go test --race -v ./tests/acceptance -timeout 30m -parallel-containers={{.PARALLEL}}

  coverage:
    desc: Run tests with coverage and generate HTML report
    cmds:
      - mkdir -p coverage
      - go test -short -coverprofile=coverage/coverage.out -covermode=atomic ./internal/...
      - go tool cover -html=coverage/coverage.out -o coverage/coverage.html
      - go tool cover -func=coverage/coverage.out | grep total | awk '{print "Total coverage:", $3}'
      - echo "Coverage report generated at coverage/coverage.html"

  coverage:badge:
    desc: Generate coverage percentage for badges
    cmds:
      - mkdir -p coverage
      - go test -short -coverprofile=coverage/coverage.out ./internal/...
      - go tool cover -func=coverage/coverage.out | grep total | awk '{print $3}'

  coverage:clean:
    desc: Remove coverage artifacts
    cmds:
      - rm -rf coverage/

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
      - terraform fmt -recursive ./examples/ 2>/dev/null || true

  lint:
    desc: Run golangci-lint to check code quality
    cmds:
      - golangci-lint run --timeout=10m ./...

  docs:
    desc: Generate documentation
    cmds:
      - go generate -tags generate ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf {{.INSTALL_DIR}}

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  debug:
    desc: Run the provider in debug mode
    deps: [build:debug]
    cmds:
      - "{{.BUILD_DIR}}/{{.BINARY}} -debug"

  build:debug:
    desc: Build with debug symbols
    cmds:
      - go build -gcflags="all=-N -l" -o {{.BUILD_DIR}}/{{.BINARY}}

  # Development workflow
  dev:
    desc: Build and install for local testing
    cmds:
      - task: deps
      - task: build
      - task: install
      - echo "Provider installed to {{.INSTALL_DIR}}"

  release:dry-run:
    desc: Test goreleaser configuration locally (no publish)
    cmds:
      - goreleaser release --snapshot --clean
