name: Response Triage
on:
  issue_comment:
    types: [created]
permissions:
  issues: write
  pull-requests: write
jobs:
  triage:
    runs-on: ubuntu-latest
    # Only run if the comment is from the issue author
    if: github.event.issue.user.id == github.event.comment.user.id
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            
            try {
              await github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number,
                name: 'waiting-response'
              });
            } catch (error) {
              // Ignore error if label doesn't exist
              if (error.status !== 404) {
                throw error;
              }
            }
